name: Check

on:
  # For new PRs, or those who are ready and/or request a review
  pull_request:
    types:
      [
        "opened",
        "edited",
        "reopened",
        "synchronize",
        "ready_for_review",
        "review_requested",
      ]
    branches: ["main"]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow simultaneous checks
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [22]
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Check broken file references in the README
        if: runner.os == 'Linux'
        uses: lycheeverse/lychee-action@v2
        with:
          args: "-n -s file README.md"
          output: "/dev/stdout"
          fail: true
          failIfEmpty: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the site
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Setup Playwright browsers
        run: yarn playwright install firefox --with-deps

      - name: Run Playwright tests
        run: yarn test:e2e

      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
